[package]
name = "user-input"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
indexmap = { version = "2.9.0", features = ["serde"] }
ratatui = "0.29.0"
serde_json = "1.0.140"
